### ISSUE TITLE
Switch to scroll layer while automouse layer is enabled

### ISSUE THREAD

**Issue by erenatas** [inorichi/zmk-pmw3610-driver#1]
Hi! I have been trying to use your driver and appreciate your work a lot! I wanted to ask the possibility of switching to scroll layer while automouse layer is activated.

What I have tried is:
1. Set 5th layer as automouse layer, 4th layer as scroll layer
2. Set a button with `&mo 4` on 5th layer

When sensor is activated, indeed it switches to automouse layer, however pressing the button to switch to scroll layer does not work.

You can find my config here: https://github.com/erenatas/zmk-config-charybdis-mini-wireless/tree/homerow-testing

**Comment by inorichi** [comment]
Have you tried reversing your automouse and scroll layers? The way ZMK works when several layers are enabled, the highest is the active one, so when you are on mouse, `&mo 4` will not do anything because it's on a lower layer.

**Comment by erenatas** [comment]
Hi! Thank you very much with the tip it works! I had no idea layer order was important. I will close this ticket. Cheers!
